config/routes.rb
AngularExample::Application.routes.draw do
  resources :participates

  resources :members

  resources :events

  match 'app' => 'app#index'

  root :to => 'app#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :cost, :description, :details, :location, :occured_at
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :balance, :description, :name
end

app/models/participate.rb
class Participate < ActiveRecord::Base
  belongs_to :event
  belongs_to :member
  # attr_accessible :title, :body
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/participates_controller.rb
class ParticipatesController < ApplicationController
  # GET /participates
  # GET /participates.json
  def index
    @participates = Participate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participates }
    end
  end

  # GET /participates/1
  # GET /participates/1.json
  def show
    @participate = Participate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participate }
    end
  end

  # GET /participates/new
  # GET /participates/new.json
  def new
    @participate = Participate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participate }
    end
  end

  # GET /participates/1/edit
  def edit
    @participate = Participate.find(params[:id])
  end

  # POST /participates
  # POST /participates.json
  def create
    @participate = Participate.new(params[:participate])

    respond_to do |format|
      if @participate.save
        format.html { redirect_to @participate, notice: 'Participate was successfully created.' }
        format.json { render json: @participate, status: :created, location: @participate }
      else
        format.html { render action: "new" }
        format.json { render json: @participate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participates/1
  # PUT /participates/1.json
  def update
    @participate = Participate.find(params[:id])

    respond_to do |format|
      if @participate.update_attributes(params[:participate])
        format.html { redirect_to @participate, notice: 'Participate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participates/1
  # DELETE /participates/1.json
  def destroy
    @participate = Participate.find(params[:id])
    @participate.destroy

    respond_to do |format|
      format.html { redirect_to participates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/views/app/index.html.erb
<!DOCTYPE html>
<html ng-app='TheApp' lang='en'>
<head>
    <title>{{app_title}}</title>
</head>
<body ng-controller="MemberController">
  <div class='container'>
    <h1 class='center-block'>Members</h1> 
   <span>Search:</span><input type="text" data-ng-model="search" />
   <br />
   <span>{{members.length}} Members</span>
   <table class="table table-striped table-hover">
        <tr ng-repeat="item in members | filter:search | orderBy:id" class='list-unstyled'>
          <td>
            <a class="col-md-1" href="#" ng-click="show(item)">{{ item.name }}</a>
          </td>
          <td>
            <span class="col-md-1">{{ item.balance }}</span>
          </td>
          <td>
            <span class="col-md-1">{{ item.description }}</span>
          </td>
          <td>
            <a class="col-md-1" href="#" ng-click="delete(item)">Delete</a>
           </td>
           <td>
            <input type='text' class="col-md-1" ng-model='item.name' />
           </td>
        </tr>
   </table>
    <div>
      New Member
    </div>
    <form name='form'>
      <div class="row">
        <span class="col-sm-2">Name:</span>
        <input class="col-md-2" type='text' name='name' ng-model='newMember.name' required />
         <span ng-show="form.name.$invalid" class="col-md-2">Name is required.</span>
    </div>
      <div class="row">
        <span class="col-sm-2">Balance:</span>
        <input class="col-md-2" type='number' ng-model='newMember.balance' name='balance' required/>
        <span ng-show="form.balance.$invalid" class="col-md-2">Balance is required and must be numeric.</span>
      </div>
      <div class="row">
        <span class="col-sm-2">Description:</span>
        <input class="col-md-2" type='text' ng-model='newMember.description' ng-maxlength=50/>
      </div>
       <button ng-click='addMember(newMember)' ng-disabled='form.$invalid'>Add Member</button>
    </form>
    </div>
  </body>
</html>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :occured_at %><br />
    <%= f.date_select :occured_at %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Occured at</th>
    <th>Cost</th>
    <th>Location</th>
    <th>Description</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.occured_at %></td>
    <td><%= event.cost %></td>
    <td><%= event.location %></td>
    <td><%= event.description %></td>
    <td><%= event.details %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Occured at:</b>
  <%= @event.occured_at %>
</p>

<p>
  <b>Cost:</b>
  <%= @event.cost %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Details:</b>
  <%= @event.details %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AngularExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Balance</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.balance %></td>
    <td><%= member.description %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Balance:</b>
  <%= @member.balance %>
</p>

<p>
  <b>Description:</b>
  <%= @member.description %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/participates/_form.html.erb
<%= form_for(@participate) do |f| %>
  <% if @participate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participate.errors.count, "error") %> prohibited this participate from being saved:</h2>

      <ul>
      <% @participate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :member %><br />
    <%= f.text_field :member %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participates/edit.html.erb
<h1>Editing participate</h1>

<%= render 'form' %>

<%= link_to 'Show', @participate %> |
<%= link_to 'Back', participates_path %>

app/views/participates/index.html.erb
<h1>Listing participates</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Member</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participates.each do |participate| %>
  <tr>
    <td><%= participate.event %></td>
    <td><%= participate.member %></td>
    <td><%= link_to 'Show', participate %></td>
    <td><%= link_to 'Edit', edit_participate_path(participate) %></td>
    <td><%= link_to 'Destroy', participate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participate', new_participate_path %>

app/views/participates/new.html.erb
<h1>New participate</h1>

<%= render 'form' %>

<%= link_to 'Back', participates_path %>

app/views/participates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @participate.event %>
</p>

<p>
  <b>Member:</b>
  <%= @participate.member %>
</p>


<%= link_to 'Edit', edit_participate_path(@participate) %> |
<%= link_to 'Back', participates_path %>